### ISSUE TITLE
Newline breaks CJK chars

### ISSUE THREAD

**Issue by hyorigo** [LeKovr/webtail#12] opened 2021-05-15 16:00 UTC
![image](https://user-images.githubusercontent.com/67533928/118370284-98bd3700-b5d9-11eb-9688-b399479eb3d0.png)

the invalid char appears around the line break --- it seems that the newline char was inserted in the middle of code point.
```
�
��
```

**Comment by LeKovr** [comment] 2021-05-18 20:44
1. How can I reproduce this behavior?
2. Here is how webtail processes lines:
```go
line := <-tw.tf.Lines // tw.tf is a https://pkg.go.dev/github.com/nxadm/tail#Tail
msg := &TailerMessage{Channel: tw.channel, Data: line.Text}
data, _ := json.Marshal(TailMessage{Type: "log", Data: msg.Data})
client.send <- data // see https://github.com/gorilla/websocket/blob/master/examples/chat/client.go#L48
```
Do you have an idea what step that newline char might be inserted in?

**Comment by hyorigo** [comment] 2021-05-22 07:59
Check this out with the default Docker image:
[test.log](https://github.com/LeKovr/webtail/files/6526040/test.log)

You can see the broken chars. And if you remove the heading 1or2, it looks normal.

**Comment by LeKovr** [comment] 2021-05-22 12:46
@hyorigo, thank you for this sample.
The cause of such behaviour lies in read buffer limit which is 180 bytes by default.
[Here](https://github.com/LeKovr/webtail/blob/master/webtail.go#L19) this default value is set
[Here](https://github.com/nxadm/tail/blob/92547340f0cc8aa12fbbb6dc2ec776190b0923ca/tail.go#L395) nxadm/tail translates it to bufio

I think there are 2 solutions:
1, Add rune support to nxadm/tail
2. Run webtail with `--skip 0` or some value which is big enough

**Comment by LeKovr** [comment] 2021-09-13 21:24
== no feedback for 3+ months. Closing ==

**Closed as completed by LeKovr** 2021-09-13 21:24 UTC
Labels: question
